### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by haxcop** [iSenseLabs/architect#1]
**Describe the bug**
Possible bug informed in the error.log file : PHP Notice: Trying to get property 'nodeValue' of non-object

481: 
**482:  $data['name'] = $dom->getElementsByTagName('name')->item(0)->nodeValue;**
483:  $data['version'] = $dom->getElementsByTagName('version')->item(0)->nodeValue;
**484:  $data['author'] = $dom->getElementsByTagName('author')->item(0)->nodeValue;**

**Environment**
- OpenCart version ... 3.0.3.6
- Architect version ... v3.0.0
- PHP 7.3

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a ocmod file in architect
2. Click on save
3. Refresh the Mod
4. Locate the error in the Error Log manager

**Expected behavior**
No issues

**Screenshots**

![Screen Shot 2021-01-13 at 2 42 57 PM](https://user-images.githubusercontent.com/7826906/104467438-3b26c880-55ae-11eb-8b02-8ceca4a5e2c9.jpg)

**Additional context**
Nothing else to add

**Comment by qaharmdz** [comment]
Based on the error message, the OcMod tags are incomplete. For basic Modification format, please refer to [Modification](https://github.com/iSenseLabs/architect/wiki/Usages#modification)
FYI, the OcMod validation on saving had been improved at 2485f40, planned for the next release.

**Comment by haxcop** [comment]
> Based on the error message, the OcMod tags are incomplete. For basic Modification format, please refer to [Modification](https://github.com/iSenseLabs/architect/wiki/Usages#modification)
> FYI, the OcMod validation on saving had been improved at #2485f40, planned for the next release.

Based on the review, the error seems to be in the order of the tags I have in one of the ocmod files are in a different order. does this order matter?

**Comment by qaharmdz** [comment]
No, the order doesn't matter. The validator only checks if the tag name exists, regardless of the order or value.
